Libraries
```{r}
#Load libraries ("plyr" needs to be loaded before "dplyr")
library(plyr)
library(mgcv)
library(dplyr)
library(varhandle)
library(psych)
library(schoolmath)
library(psychometric)
library(openxlsx)
```

Load data
```{r}

subjData=readRDS("/Users/path/to/data/hydra_subjData.rds")

filename <- "/Users/path/to/data/Hydra_Standardized_Brain_S_8.29.23.xlsx"  # Provide the desired file path
wb <- createWorkbook()


```

Create variable that reorders the group variable of interest to make S2 the comparison group
```{r}
#Total sample size
n <- nrow(subjData)

#Reorder the group variable of interest to make S2 the comparison group.
subjData$Hydra_k2_reordered <- factor(subjData$Hydra_k2, levels=c("2","1","0"))
levels(subjData$Hydra_k2_reordered) <- list("S2" ="2", "S1" ="1", "TD" ="0")

#convert Hydra_k2 to factor
subjData$Hydra_k2 <- factor(subjData$Hydra_k2)
levels(subjData$Hydra_k2) <- list("TD" ="0", "S1" ="1", "S2" ="2")

# Convert variable class types
subjData$mom_education_b = as.numeric(subjData$mom_education_b)
subjData$FEMALE_b <- factor(subjData$FEMALE_b)
subjData$mri_info_deviceserialnumber_b <- as.factor(subjData$mri_info_deviceserialnumber_b)


```

############################## SENSITIVITY BASELINE  #################################



Cortical Vol - TICV baseline
```{r}
 #Clean up environment if desired
rm(list=setdiff(ls(),c("subjData","n",'filename','wb')))

# Define "adjust" variable. This goes into the lm model and minimizes script editing
adjust = subjData$TICV_b/1000

#Get variable names
volRegions <- colnames(subjData[,which(colnames(subjData)=="smri_vol_cdk_banksstslh_b"):which(colnames(subjData)=="smri_vol_cdk_insularh_b")])

svolRegions <- c("smri_vol_scs_crbcortexlh_b",	"smri_vol_scs_tplh_b",	"smri_vol_scs_caudatelh_b",	"smri_vol_scs_putamenlh_b",	"smri_vol_scs_pallidumlh_b",	"smri_vol_scs_bstem_b",	"smri_vol_scs_hpuslh_b",	"smri_vol_scs_amygdalalh_b",	"smri_vol_scs_aal_b",	"smri_vol_scs_vedclh_b",	"smri_vol_scs_crbcortexrh_b",	"smri_vol_scs_tprh_b",	"smri_vol_scs_caudaterh_b",	"smri_vol_scs_putamenrh_b",	"smri_vol_scs_pallidumrh_b",	"smri_vol_scs_hpusrh_b",	"smri_vol_scs_amygdalarh_b",	"smri_vol_scs_aar_b",	"smri_vol_scs_vedcrh_b")


volRegions <- append(volRegions, svolRegions, after = length(volRegions))

#See adjust variable here. 
volLm <- lapply(volRegions, function(x) {
  lm(substitute(i ~ age_b + FEMALE_b +   Hydra_k2 + mri_info_deviceserialnumber_b + adjust ,  list(i = as.name(x))), data=subjData)
})

#Look at model summaries
volLmSumm <- lapply(volLm, summary)

##Pass the results to the anova() omnibus test
volAnova <- lapply(volLm, anova)

#Pull the p-values
vol_p <- sapply(volAnova, function(v) v$"Pr(>F)"[3])

#Convert to data frame
vol_p <- as.data.frame(vol_p)

#Add row names for ease of viewing
rownames(vol_p) <- volRegions

#Print original p-values to three decimal places
vol_p_round <- round(vol_p,3)


##FDR correction across all omnibus anova tests
vol_p_fdr <- p.adjust(vol_p[,1],method="fdr")

#Convert to data frame
vol_p_fdr <- as.data.frame(vol_p_fdr)

#Print fdr-corrected p-values to three decimal places
vol_p_fdr_round <- round(vol_p_fdr,3)

#Add region names
volNames <- as.data.frame(volRegions)
vol_omnibus <- cbind(volNames,vol_p_fdr_round)

#Trim table to only regions that passed FDR correction
vol_omnibus_signif <- vol_omnibus[vol_p_fdr<0.05,]



##Run same model with Hydra_k2_reordered to make S2 the comparison group in order to see S1 vs S2 differences 
volLm_reordered <- lapply(volRegions, function(x) {
  lm(substitute(i ~ age_b + FEMALE_b +  Hydra_k2_reordered  + mri_info_deviceserialnumber_b + adjust, list(i = as.name(x))), data=subjData)
})

#Look at model summaries
volLmSumm_reordered <- lapply(volLm_reordered, summary)

##Pairwise comparisons
#Pull uncorrected p-values
vol_S1vsTd <- sapply(volLm, function(v) summary(v)$coefficients[4,4])
vol_S2vsTd <- sapply(volLm, function(v) summary(v)$coefficients[5,4])
vol_S1vsS2 <- sapply(volLm_reordered, function(v) summary(v)$coefficients[4,4])



#Combine the pairwise p values
vol_pairs <- cbind(vol_S1vsTd,vol_S2vsTd,vol_S1vsS2)

#Convert to data frame
vol_pairs <- as.data.frame(vol_pairs)

#Add row names for ease of viewing
rownames(vol_pairs) <- volRegions

#Print original p-values to three decimal places
vol_pairs_round <- round(vol_pairs,3)


##FDR correction across the three pairwise group comparisons (S1vsTd, S2vsTd, and S1vsS2)
#Create an empty table for the fdr results
vol_fdrTable<-as.data.frame(matrix(nrow=length(volRegions),ncol=3))
colnames(vol_fdrTable)[1]<-"vol_S1vsTd_pfdr"
colnames(vol_fdrTable)[2]<-"vol_S2vsTd_pfdr"
colnames(vol_fdrTable)[3]<-"vol_S1vsS2_pfdr"

#FDR correct across rows
for(i in 1:nrow(vol_pairs)) {
  row <- vol_pairs[i,]
  vol_fdrTable[i,] <- p.adjust(vol_pairs[i,],method="fdr")
}

#Print fdr-corrected p-values to three decimal places
vol_fdrTable_round <- round(vol_fdrTable,3)

#Add region names
vol_pairwise <- cbind(volNames,vol_fdrTable_round)

#Trim table to only regions that passed FDR correction for the omnibus test
vol_pairwise_signif <- vol_pairwise[vol_p_fdr<0.05,]


```
Create Tables - 
```{r}

# Specify file and sheet names
sheet_name <- "Sen_TICV_b"         
num_models <- length(volLm)
anova_model = volAnova
model = volLm
modelSumm = volLmSumm
model_reordered = volLm_reordered
modelSumm_reordered = volLmSumm_reordered
pairwise_p = vol_fdrTable_round
rnames = volRegions
var = 5  # var = number of variables included in lm model (age, female, bifactors, site/scanner, & adjust variable)

# ANOVA
Lm_F <- lapply(anova_model, function(x) {(x$`F value`[3])})
Lm_p <- lapply(anova_model, function(x) {(x$`Pr(>F)`[3])})


## Confidence intevals
Lm_rsq_CI <- lapply(modelSumm, function(x) {CI.Rsq(x$r.squared,n,var,.95)})


#Estimate Se T p 
S1Td_stats <- lapply(model, function(v) summary(v)$coefficients[4,])
S2Td_stats <- lapply(model, function(v) summary(v)$coefficients[5,])
S1S2_stats <- lapply(model_reordered, function(v) summary(v)$coefficients[4,])



df <- data.frame(F_statistic = numeric(num_models),
                 Anova_p = numeric(num_models), 
                 #T1
                 Est_T1 = numeric(num_models), 
                 SE_T1 = numeric(num_models), 
                 t_T1 = numeric(num_models), 
                 p_T1 = numeric(num_models), 
                 #T2
                 Est_T2 = numeric(num_models), 
                 SE_T2 = numeric(num_models), 
                 t_T2 = numeric(num_models), 
                 p_T2 = numeric(num_models),
                 #12
                 Est_12 = numeric(num_models), 
                 SE_12 = numeric(num_models), 
                 t_12 = numeric(num_models), 
                 p_12 = numeric(num_models),
                 R_squared = numeric(num_models), 
                 LCL = numeric(num_models), 
                 UCL = numeric(num_models))

# Standardize betas
stBeta = lapply(model, function(x) {(lm.beta(x))})
stBeta_reordered = lapply(model_reordered, function(x) {(lm.beta(x))})

for (i in 1:num_models) {
  df[i, "Est_T1"] <- stBeta[[i]]$standardized.coefficients[4]
  df[i, "Est_T2"] <- stBeta[[i]]$standardized.coefficients[5]
  df[i, "Est_12"] <- stBeta_reordered[[i]]$standardized.coefficients[4]
  df[i, "F_statistic"] <- Lm_F[[i]]
  df[i, "Anova_p"] <- Lm_p[[i]]
  #df[i, "Est_T1"] <- S1Td_stats[[i]][1]
  df[i, "SE_T1"] <- S1Td_stats[[i]][2]
  df[i, "t_T1"] <- S1Td_stats[[i]][3]
  df[i, "p_T1"] <- NA
  #df[i, "Est_T2"] <- S2Td_stats[[i]][1]
  df[i, "SE_T2"] <- S2Td_stats[[i]][2]
  df[i, "t_T2"] <- S2Td_stats[[i]][3]
  df[i, "p_T2"] <- NA
  #df[i, "Est_12"] <- S1S2_stats[[i]][1]
  df[i, "SE_12"] <- S1S2_stats[[i]][2]
  df[i, "t_12"] <- S1S2_stats[[i]][3]
  df[i, "p_12"] <- NA
  df[i, "R_squared"] <- Lm_rsq_CI[[i]]$Rsq
  df[i, "LCL"] <- Lm_rsq_CI[[i]]$LCL
  df[i, "UCL"] <- Lm_rsq_CI[[i]]$UCL
}


df['p_T1']<-  pairwise_p[1]
df['p_T2']<-  pairwise_p[2]
df['p_12']<-  pairwise_p[3]

rownames(df)<- rnames


# Add a new sheet to the workbook
addWorksheet(wb, sheetName = sheet_name)

# Write the data frame to the new sheet, including row index names
writeData(wb, sheet = sheet_name, x= df,row.names = TRUE,col.names = TRUE)


```




CT 
```{r}

#Clean up environment if desired
rm(list=setdiff(ls(),c("subjData","n",'filename','wb')))

 # Define "adjust" variable. This goes into the lm model and minimizes script editing 
adjust  <- subjData$smri_thick_cdk_mean_b

#Get variable names

volRegions <- colnames(subjData[,which(colnames(subjData)=="smri_thick_cdk_banksstslh_b"):which(colnames(subjData)=="smri_thick_cdk_insularh_b")])


volLm <- lapply(volRegions,function(x){
  lm(substitute(i~age_b+FEMALE_b + Hydra_k2 + mri_info_deviceserialnumber_b + adjust ,list(i = as.name(x))),data = subjData)
})


#Look at model summaries
volLmSumm <- lapply(volLm, summary)

##Pass the results to the anova() function to fit ANOVAs 
#These are your omnibus ANOVA tests (tells you if the three groups are significantly different)
volAnova <- lapply(volLm, anova)

#Pull the p-values
vol_p <- sapply(volAnova, function(v) v$"Pr(>F)"[3])


#Convert to data frame
vol_p <- as.data.frame(vol_p)

#Add row names for ease of viewing
rownames(vol_p) <- volRegions

#Print original p-values to three decimal places
vol_p_round <- round(vol_p,3)



##FDR correction across all omnibus anova tests
#FDR correct p-values
vol_p_fdr <- p.adjust(vol_p[,1],method="fdr")

#Convert to data frame
vol_p_fdr <- as.data.frame(vol_p_fdr)

#Print fdr-corrected p-values to three decimal places
vol_p_fdr_round <- round(vol_p_fdr,3)

#Add region names
volNames <- as.data.frame(volRegions)
vol_omnibus <- cbind(volNames,vol_p_fdr_round)

#Trim table to only regions that passed FDR correction
vol_omnibus_signif <- vol_omnibus[vol_p_fdr<0.05,]


#Run same model with Hydra_k2_reordered to make S2 the comparison group in order to see S1 vs S2 differences in the model. This model will provide estimates and p-values for S1-S2.

volLm_reordered <- lapply(volRegions,function(x){
  lm(substitute(i~age_b+FEMALE_b + Hydra_k2_reordered + mri_info_deviceserialnumber_b + adjust,list(i = as.name(x))),data = subjData)
})


#Look at model summaries
volLmSumm_reordered <- lapply(volLm_reordered, summary)

##Pairwise comparisons
#Pull uncorrected p-values
vol_S1vsTd <- sapply(volLm, function(v) summary(v)$coefficients[4,4])
vol_S2vsTd <- sapply(volLm, function(v) summary(v)$coefficients[5,4])
vol_S1vsS2 <- sapply(volLm_reordered, function(v) summary(v)$coefficients[4,4])

#Combine the pairwise p values
vol_pairs <- cbind(vol_S1vsTd,vol_S2vsTd,vol_S1vsS2)

#Convert to data frame
vol_pairs <- as.data.frame(vol_pairs)

#Add row names for ease of viewing
rownames(vol_pairs) <- volRegions

#Print original p-values to three decimal places
vol_pairs_round <- round(vol_pairs,3)


##FDR correction across the three pairwise group comparisons (S1vsTd, S2vsTd, and S1vsS2)
#Create an empty table for the fdr results
vol_fdrTable<-as.data.frame(matrix(nrow=68,ncol=3))
colnames(vol_fdrTable)[1]<-"vol_S1vsTd_pfdr"
colnames(vol_fdrTable)[2]<-"vol_S2vsTd_pfdr"
colnames(vol_fdrTable)[3]<-"vol_S1vsS2_pfdr"

#FDR correct across rows
for(i in 1:nrow(vol_pairs)) {
    row <- vol_pairs[i,]
    vol_fdrTable[i,] <- p.adjust(vol_pairs[i,],method="fdr")
}

#Print fdr-corrected p-values to three decimal places
vol_fdrTable_round <- round(vol_fdrTable,3)

#Add region names
vol_pairwise <- cbind(volNames,vol_fdrTable_round)

#Trim table to only regions that passed FDR correction for the omnibus test
vol_pairwise_signif <- vol_pairwise[vol_p_fdr<0.05,]



```
Create Tables - CT baseline
```{r}

# Specify file and sheet names
sheet_name <- "Sen_CT_b"         
num_models <- length(volLm)
anova_model = volAnova
model = volLm
modelSumm = volLmSumm
model_reordered = volLm_reordered
modelSumm_reordered = volLmSumm_reordered
pairwise_p = vol_fdrTable_round
rnames = volRegions
var = 5  # var = number of variables included in lm model (age, female, bifactors, site/scanner, & adjust variable)

# ANOVA
Lm_F <- lapply(anova_model, function(x) {(x$`F value`[3])})
Lm_p <- lapply(anova_model, function(x) {(x$`Pr(>F)`[3])})


## Confidence intevals
Lm_rsq_CI <- lapply(modelSumm, function(x) {CI.Rsq(x$r.squared,n,var,.95)})

#Estimate Se T p 
S1Td_stats <- lapply(model, function(v) summary(v)$coefficients[4,])
S2Td_stats <- lapply(model, function(v) summary(v)$coefficients[5,])
S1S2_stats <- lapply(model_reordered, function(v) summary(v)$coefficients[4,])



df <- data.frame(F_statistic = numeric(num_models),
                 Anova_p = numeric(num_models), 
                 #T1
                 Est_T1 = numeric(num_models), 
                 SE_T1 = numeric(num_models), 
                 t_T1 = numeric(num_models), 
                 p_T1 = numeric(num_models), 
                 #T2
                 Est_T2 = numeric(num_models), 
                 SE_T2 = numeric(num_models), 
                 t_T2 = numeric(num_models), 
                 p_T2 = numeric(num_models),
                 #12
                 Est_12 = numeric(num_models), 
                 SE_12 = numeric(num_models), 
                 t_12 = numeric(num_models), 
                 p_12 = numeric(num_models),
                 R_squared = numeric(num_models), 
                 LCL = numeric(num_models), 
                 UCL = numeric(num_models))

# Standardize betas
stBeta = lapply(model, function(x) {(lm.beta(x))})
stBeta_reordered = lapply(model_reordered, function(x) {(lm.beta(x))})

for (i in 1:num_models) {
  df[i, "Est_T1"] <- stBeta[[i]]$standardized.coefficients[4]
  df[i, "Est_T2"] <- stBeta[[i]]$standardized.coefficients[5]
  df[i, "Est_12"] <- stBeta_reordered[[i]]$standardized.coefficients[4]
  df[i, "F_statistic"] <- Lm_F[[i]]
  df[i, "Anova_p"] <- Lm_p[[i]]
  df[i, "R_squared"] <- Lm_rsq_CI[[i]]$Rsq
  df[i, "LCL"] <- Lm_rsq_CI[[i]]$LCL
  df[i, "UCL"] <- Lm_rsq_CI[[i]]$UCL
  #df[i, "Est_T1"] <- S1Td_stats[[i]][1]
  df[i, "SE_T1"] <- S1Td_stats[[i]][2]
  df[i, "t_T1"] <- S1Td_stats[[i]][3]
  df[i, "p_T1"] <- NA
  #df[i, "Est_T2"] <- S2Td_stats[[i]][1]
  df[i, "SE_T2"] <- S2Td_stats[[i]][2]
  df[i, "t_T2"] <- S2Td_stats[[i]][3]
  df[i, "p_T2"] <- NA
  #df[i, "Est_12"] <- S1S2_stats[[i]][1]
  df[i, "SE_12"] <- S1S2_stats[[i]][2]
  df[i, "t_12"] <- S1S2_stats[[i]][3]
  df[i, "p_12"] <- NA
}


df['p_T1']<-  pairwise_p[1]
df['p_T2']<-  pairwise_p[2]
df['p_12']<-  pairwise_p[3]

rownames(df)<- rnames


# Add a new sheet to the workbook
addWorksheet(wb, sheetName = sheet_name)

# Write the data frame to the new sheet, including row index names
writeData(wb, sheet = sheet_name, x= df,row.names = TRUE,col.names = TRUE)


```






############################## SENSITIVITY YEAR 2  #################################

Cortical Vol - ICV year 2 
```{r}
# Clean up environment if desired
rm(list=setdiff(ls(),c("subjData","n",'filename','wb')))

 # Define "adjust" variable. This goes into the lm model and minimizes script editing
adjust = subjData$TICV_2/1000

#Change age variable to make sure it is of the correct time point 
age = subjData$age_2

#Get variable names
volRegions <- colnames(subjData[,which(colnames(subjData)=="smri_vol_cdk_banksstslh_2"):which(colnames(subjData)=="smri_vol_cdk_insularh_2")])


svolRegions <- c("smri_vol_scs_crbcortexlh_2",	"smri_vol_scs_tplh_2",	"smri_vol_scs_caudatelh_2",	"smri_vol_scs_putamenlh_2",	"smri_vol_scs_pallidumlh_2",	"smri_vol_scs_bstem_2",	"smri_vol_scs_hpuslh_2",	"smri_vol_scs_amygdalalh_2",	"smri_vol_scs_aal_2",	"smri_vol_scs_vedclh_2",	"smri_vol_scs_crbcortexrh_2",	"smri_vol_scs_tprh_2",	"smri_vol_scs_caudaterh_2",	"smri_vol_scs_putamenrh_2",	"smri_vol_scs_pallidumrh_2",	"smri_vol_scs_hpusrh_2",	"smri_vol_scs_amygdalarh_2",	"smri_vol_scs_aar_2",	"smri_vol_scs_vedcrh_2")


volRegions <- append(volRegions, svolRegions, after = length(volRegions))

volLm <- lapply(volRegions, function(x) {
  lm(substitute(i ~ age + FEMALE_b +   Hydra_k2  + mri_info_deviceserialnumber_b + adjust ,  list(i = as.name(x))), data=subjData)
})

#Look at model summaries
volLmSumm <- lapply(volLm, summary)

##Pass the results to the anova() omnibus test
volAnova <- lapply(volLm, anova)

#Pull the p-values
vol_p <- sapply(volAnova, function(v) v$"Pr(>F)"[3])

#Convert to data frame
vol_p <- as.data.frame(vol_p)

#Add row names for ease of viewing
rownames(vol_p) <- volRegions

#Print original p-values to three decimal places
vol_p_round <- round(vol_p,3)


##FDR correction across all omnibus anova tests
vol_p_fdr <- p.adjust(vol_p[,1],method="fdr")

#Convert to data frame
vol_p_fdr <- as.data.frame(vol_p_fdr)

#Print fdr-corrected p-values to three decimal places
vol_p_fdr_round <- round(vol_p_fdr,3)

#Add region names
volNames <- as.data.frame(volRegions)
vol_omnibus <- cbind(volNames,vol_p_fdr_round)

#Trim table to only regions that passed FDR correction
vol_omnibus_signif <- vol_omnibus[vol_p_fdr<0.05,]



##Run same model with Hydra_k2_reordered to make S2 the comparison group in order to see S1 vs S2 differences 
volLm_reordered <- lapply(volRegions, function(x) {
  lm(substitute(i ~ age + FEMALE_b +  Hydra_k2_reordered  + mri_info_deviceserialnumber_b + adjust, list(i = as.name(x))), data=subjData)
})

#Look at model summaries
volLmSumm_reordered <- lapply(volLm_reordered, summary)

##Pairwise comparisons
#Pull uncorrected p-values
vol_S1vsTd <- sapply(volLm, function(v) summary(v)$coefficients[4,4])
vol_S2vsTd <- sapply(volLm, function(v) summary(v)$coefficients[5,4])
vol_S1vsS2 <- sapply(volLm_reordered, function(v) summary(v)$coefficients[4,4])



#Combine the pairwise p values
vol_pairs <- cbind(vol_S1vsTd,vol_S2vsTd,vol_S1vsS2)

#Convert to data frame
vol_pairs <- as.data.frame(vol_pairs)

#Add row names for ease of viewing
rownames(vol_pairs) <- volRegions

#Print original p-values to three decimal places
vol_pairs_round <- round(vol_pairs,3)


##FDR correction across the three pairwise group comparisons (S1vsTd, S2vsTd, and S1vsS2)
#Create an empty table for the fdr results
vol_fdrTable<-as.data.frame(matrix(nrow=length(volRegions),ncol=3))
colnames(vol_fdrTable)[1]<-"vol_S1vsTd_pfdr"
colnames(vol_fdrTable)[2]<-"vol_S2vsTd_pfdr"
colnames(vol_fdrTable)[3]<-"vol_S1vsS2_pfdr"

#FDR correct across rows
for(i in 1:nrow(vol_pairs)) {
  row <- vol_pairs[i,]
  vol_fdrTable[i,] <- p.adjust(vol_pairs[i,],method="fdr")
}

#Print fdr-corrected p-values to three decimal places
vol_fdrTable_round <- round(vol_fdrTable,3)

#Add region names
vol_pairwise <- cbind(volNames,vol_fdrTable_round)

#Trim table to only regions that passed FDR correction for the omnibus test
vol_pairwise_signif <- vol_pairwise[vol_p_fdr<0.05,]


```
Create Tables - TICV year 2
```{r}

# Specify file and sheet names
sheet_name <- "Sen_TICV_2"         
num_models <- length(volLm)
anova_model = volAnova
model = volLm
modelSumm = volLmSumm
model_reordered = volLm_reordered
modelSumm_reordered = volLmSumm_reordered
pairwise_p = vol_fdrTable_round
rnames = volRegions
var = 5  # var = number of variables included in lm model (age, female, bifactors, site/scanner & adjust variable)

# ANOVA
Lm_F <- lapply(anova_model, function(x) {(x$`F value`[3])})
Lm_p <- lapply(anova_model, function(x) {(x$`Pr(>F)`[3])})


## Confidence intevals
Lm_rsq_CI <- lapply(modelSumm, function(x) {CI.Rsq(x$r.squared,n,var,.95)})


#Estimate Se T p 
S1Td_stats <- lapply(model, function(v) summary(v)$coefficients[4,])
S2Td_stats <- lapply(model, function(v) summary(v)$coefficients[5,])
S1S2_stats <- lapply(model_reordered, function(v) summary(v)$coefficients[4,])



df <- data.frame(F_statistic = numeric(num_models),
                 Anova_p = numeric(num_models), 
                 #T1
                 Est_T1 = numeric(num_models), 
                 SE_T1 = numeric(num_models), 
                 t_T1 = numeric(num_models), 
                 p_T1 = numeric(num_models), 
                 #T2
                 Est_T2 = numeric(num_models), 
                 SE_T2 = numeric(num_models), 
                 t_T2 = numeric(num_models), 
                 p_T2 = numeric(num_models),
                 #12
                 Est_12 = numeric(num_models), 
                 SE_12 = numeric(num_models), 
                 t_12 = numeric(num_models), 
                 p_12 = numeric(num_models),
                 R_squared = numeric(num_models), 
                 LCL = numeric(num_models), 
                 UCL = numeric(num_models))

# Standardize betas
stBeta = lapply(model, function(x) {(lm.beta(x))})
stBeta_reordered = lapply(model_reordered, function(x) {(lm.beta(x))})

for (i in 1:num_models) {
  df[i, "Est_T1"] <- stBeta[[i]]$standardized.coefficients[4]
  df[i, "Est_T2"] <- stBeta[[i]]$standardized.coefficients[5]
  df[i, "Est_12"] <- stBeta_reordered[[i]]$standardized.coefficients[4]
  df[i, "F_statistic"] <- Lm_F[[i]]
  df[i, "Anova_p"] <- Lm_p[[i]]
  #df[i, "Est_T1"] <- S1Td_stats[[i]][1]
  df[i, "SE_T1"] <- S1Td_stats[[i]][2]
  df[i, "t_T1"] <- S1Td_stats[[i]][3]
  df[i, "p_T1"] <- NA
  #df[i, "Est_T2"] <- S2Td_stats[[i]][1]
  df[i, "SE_T2"] <- S2Td_stats[[i]][2]
  df[i, "t_T2"] <- S2Td_stats[[i]][3]
  df[i, "p_T2"] <- NA
  #df[i, "Est_12"] <- S1S2_stats[[i]][1]
  df[i, "SE_12"] <- S1S2_stats[[i]][2]
  df[i, "t_12"] <- S1S2_stats[[i]][3]
  df[i, "p_12"] <- NA
  df[i, "R_squared"] <- Lm_rsq_CI[[i]]$Rsq
  df[i, "LCL"] <- Lm_rsq_CI[[i]]$LCL
  df[i, "UCL"] <- Lm_rsq_CI[[i]]$UCL
}


df['p_T1']<-  pairwise_p[1]
df['p_T2']<-  pairwise_p[2]
df['p_12']<-  pairwise_p[3]

rownames(df)<- rnames


# Add a new sheet to the workbook
addWorksheet(wb, sheetName = sheet_name)

# Write the data frame to the new sheet, including row index names
writeData(wb, sheet = sheet_name, x= df,row.names = TRUE,col.names = TRUE)

 
```




CT  - year 2
```{r}
 #Clean up environment if desired
rm(list=setdiff(ls(),c("subjData","n",'filename','wb')))

 # Define "adjust" variable. This goes into the lm model and minimizes script editing
adjust  <- subjData$smri_thick_cdk_mean_2
age = subjData$age_2

#Get variable names

volRegions <- colnames(subjData[,which(colnames(subjData)=="smri_thick_cdk_banksstslh_b"):which(colnames(subjData)=="smri_thick_cdk_insularh_b")])


volLm <- lapply(volRegions,function(x){
  lm(substitute(i~age +FEMALE_b + Hydra_k2 + mri_info_deviceserialnumber_b + adjust ,list(i = as.name(x))),data = subjData)
})


#Look at model summaries
volLmSumm <- lapply(volLm, summary)

##Pass the results to the anova() function to fit ANOVAs 
#These are your omnibus ANOVA tests (tells you if the three groups are significantly different)
volAnova <- lapply(volLm, anova)

#Pull the p-values
vol_p <- sapply(volAnova, function(v) v$"Pr(>F)"[3])


#Convert to data frame
vol_p <- as.data.frame(vol_p)

#Add row names for ease of viewing
rownames(vol_p) <- volRegions

#Print original p-values to three decimal places
vol_p_round <- round(vol_p,3)



##FDR correction across all omnibus anova tests
#FDR correct p-values
vol_p_fdr <- p.adjust(vol_p[,1],method="fdr")

#Convert to data frame
vol_p_fdr <- as.data.frame(vol_p_fdr)

#Print fdr-corrected p-values to three decimal places
vol_p_fdr_round <- round(vol_p_fdr,3)

#Add region names
volNames <- as.data.frame(volRegions)
vol_omnibus <- cbind(volNames,vol_p_fdr_round)

#Trim table to only regions that passed FDR correction
vol_omnibus_signif <- vol_omnibus[vol_p_fdr<0.05,]


#Run same model with Hydra_k2_reordered to make S2 the comparison group in order to see S1 vs S2 differences in the model. This model will provide estimates and p-values for S1-S2.

volLm_reordered <- lapply(volRegions,function(x){
  lm(substitute(i~age+FEMALE_b + Hydra_k2_reordered + mri_info_deviceserialnumber_b + adjust,list(i = as.name(x))),data = subjData)
})


#Look at model summaries
volLmSumm_reordered <- lapply(volLm_reordered, summary)


##Pairwise comparisons
#Pull uncorrected p-values
vol_S1vsTd <- sapply(volLm, function(v) summary(v)$coefficients[4,4])
vol_S2vsTd <- sapply(volLm, function(v) summary(v)$coefficients[5,4])
vol_S1vsS2 <- sapply(volLm_reordered, function(v) summary(v)$coefficients[4,4])

#Combine the pairwise p values
vol_pairs <- cbind(vol_S1vsTd,vol_S2vsTd,vol_S1vsS2)

#Convert to data frame
vol_pairs <- as.data.frame(vol_pairs)

#Add row names for ease of viewing
rownames(vol_pairs) <- volRegions

#Print original p-values to three decimal places
vol_pairs_round <- round(vol_pairs,3)


##FDR correction across the three pairwise group comparisons (S1vsTd, S2vsTd, and S1vsS2)
#Create an empty table for the fdr results
vol_fdrTable<-as.data.frame(matrix(nrow=68,ncol=3))
colnames(vol_fdrTable)[1]<-"vol_S1vsTd_pfdr"
colnames(vol_fdrTable)[2]<-"vol_S2vsTd_pfdr"
colnames(vol_fdrTable)[3]<-"vol_S1vsS2_pfdr"

#FDR correct across rows
for(i in 1:nrow(vol_pairs)) {
    row <- vol_pairs[i,]
    vol_fdrTable[i,] <- p.adjust(vol_pairs[i,],method="fdr")
}

#Print fdr-corrected p-values to three decimal places
vol_fdrTable_round <- round(vol_fdrTable,3)

#Add region names
vol_pairwise <- cbind(volNames,vol_fdrTable_round)

#Trim table to only regions that passed FDR correction for the omnibus test
vol_pairwise_signif <- vol_pairwise[vol_p_fdr<0.05,]


```
Create Tables - CT baseline
```{r}

# Specify file and sheet names
sheet_name <- "Sen_CT_2"         
num_models <- length(volLm)
anova_model = volAnova
model = volLm
modelSumm = volLmSumm
model_reordered = volLm_reordered
modelSumm_reordered = volLmSumm_reordered
pairwise_p = vol_fdrTable_round
rnames = volRegions
var = 5  # var = number of variables included in lm model (age, female, bifactors, site/scanner, & adjust variable)

# ANOVA
Lm_F <- lapply(anova_model, function(x) {(x$`F value`[3])})
Lm_p <- lapply(anova_model, function(x) {(x$`Pr(>F)`[3])})


## Confidence intevals
Lm_rsq_CI <- lapply(modelSumm, function(x) {CI.Rsq(x$r.squared,n,var,.95)})

#Estimate Se T p 
S1Td_stats <- lapply(model, function(v) summary(v)$coefficients[4,])
S2Td_stats <- lapply(model, function(v) summary(v)$coefficients[5,])
S1S2_stats <- lapply(model_reordered, function(v) summary(v)$coefficients[4,])



df <- data.frame(F_statistic = numeric(num_models),
                 Anova_p = numeric(num_models), 
                 #T1
                 Est_T1 = numeric(num_models), 
                 SE_T1 = numeric(num_models), 
                 t_T1 = numeric(num_models), 
                 p_T1 = numeric(num_models), 
                 #T2
                 Est_T2 = numeric(num_models), 
                 SE_T2 = numeric(num_models), 
                 t_T2 = numeric(num_models), 
                 p_T2 = numeric(num_models),
                 #12
                 Est_12 = numeric(num_models), 
                 SE_12 = numeric(num_models), 
                 t_12 = numeric(num_models), 
                 p_12 = numeric(num_models),
                 R_squared = numeric(num_models), 
                 LCL = numeric(num_models), 
                 UCL = numeric(num_models))

# Standardize betas
stBeta = lapply(model, function(x) {(lm.beta(x))})
stBeta_reordered = lapply(model_reordered, function(x) {(lm.beta(x))})

for (i in 1:num_models) {
  df[i, "Est_T1"] <- stBeta[[i]]$standardized.coefficients[4]
  df[i, "Est_T2"] <- stBeta[[i]]$standardized.coefficients[5]
  df[i, "Est_12"] <- stBeta_reordered[[i]]$standardized.coefficients[4]
  df[i, "F_statistic"] <- Lm_F[[i]]
  df[i, "Anova_p"] <- Lm_p[[i]]
  df[i, "R_squared"] <- Lm_rsq_CI[[i]]$Rsq
  df[i, "LCL"] <- Lm_rsq_CI[[i]]$LCL
  df[i, "UCL"] <- Lm_rsq_CI[[i]]$UCL
  #df[i, "Est_T1"] <- S1Td_stats[[i]][1]
  df[i, "SE_T1"] <- S1Td_stats[[i]][2]
  df[i, "t_T1"] <- S1Td_stats[[i]][3]
  #df[i, "p_T1"] <- S1Td_stats[[i]][4]
  df[i, "p_T1"] <- NA
  #df[i, "Est_T2"] <- S2Td_stats[[i]][1]
  df[i, "SE_T2"] <- S2Td_stats[[i]][2]
  df[i, "t_T2"] <- S2Td_stats[[i]][3]
  df[i, "p_T2"] <- NA
  #df[i, "Est_12"] <- S1S2_stats[[i]][1]
  df[i, "SE_12"] <- S1S2_stats[[i]][2]
  df[i, "t_12"] <- S1S2_stats[[i]][3]
  df[i, "p_12"] <- NA
}


df['p_T1']<-  pairwise_p[1]
df['p_T2']<-  pairwise_p[2]
df['p_12']<-  pairwise_p[3]

rownames(df)<- rnames

# Add a new sheet to the workbook
addWorksheet(wb, sheetName = sheet_name)

# Write the data frame to the new sheet, including row index names
writeData(wb, sheet = sheet_name, x= df,row.names = TRUE,col.names = TRUE)

```



```{r}
saveWorkbook(wb, filename)
```